server:
  port: 8083
  timeout: 5s
  idle_timeout: 60s

database:
  host: db
  port: 5432
  name: avito_db
  user: myuser
  password: # leave blank if you want to load from the $DB_PASSWORD environment variable

logger:
  level: info # debug / info / prod

auth:
  jwt_secret:  # Use the $JWT_SECRET environment variable for security